export let ADD_ITEM_TO_BASKET = 'ADD_ITEM_TO_BASKET';
export let DELETE_ITEM_FROM_BASKET = 'DELETE_ITEM_FROM_BASKET';
export let CHANGE_ACTIVE_TAG = 'CHANGE_ACTIVE_TAG';
export let OPEN_CLOSE_BASKET = 'OPEN_CLOSE_BASKET';
export let GET_DATA_START = 'GET_DATA_START';
export let GET_DATA_SUCCES = 'GET_DATA_SUCCES';
export let GET_DATA_ERROR = 'GET_DATA_ERROR';